# Generated by Django 4.1 on 2022-09-14 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField(max_length=120)),
                ('category_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='breed_cat', to='api.category')),
            ],
        ),
    ]
